### ISSUE TITLE
Clarification of where to document <Equipment> when common to multiple channels

### ISSUE THREAD

**Issue by chad-iris** [FDSN/StationXML#101]
Documentation for Station->Equipment currently reads:
```
Equipment used by all channels at a station.
```

With docs for Channel->Equipment reading:
```
If the Equipment is entered at the Station level, it is not necessary to do it for each Channel, 
unless you have differences in equipment. If using a preamplifier, sensor, or datalogger, 
use their appropriate fields instead.
```

In my opinion, the sensor, data logger, and preamplifier should always be specified at the Channel level when present.  Even though this may lead to some redundancy, it will provide consistency for metadata readers to find these important fields.  I think this was the intention of the docs, but it could be more clear.

I propose the following changes for clarity:

For Station->Equipment:
```
Equipment used by all channels at a station, except for equipment that has type-specific
fields at the Channel level such as sensor, data logger and preamplifier.
```

For Channel->Equipment:
```
Any equipment that does not have type-specific fields.  Equipment such as sensor, data logger and 
preamplifier that has type-specific fields should be documented in those structures.
If the Equipment is entered at the Station level, it is not necessary to include it for each Channel, 
unless you have differences in equipment.
```

**Comment by PetrColinSky** [comment]
I generally agree with what @crotwell suggests. My comments to this: I don't like redundancy, so repeating all PaZ and FIR filter coefficients 3 times for a classical seismic sensors seems impractical to me. Generally, each component of a seismic sensor could have different transfer function, sure. In practice, the &lt;Response&gt; is copied-pasted 3 times for all 3 channels. But obviously, one cannot set it at the &lt;Station&gt; level, as station can have more instruments. In addition, if we say, that "sensor, data logger and preamplifier" should be at the &lt;Channel&gt; level as well, what is left for the &lt;Station&gt; level then? I would completely remove the &lt;Equipment&gt; from the &lt;Station&gt; level. To me, the nicest solution would be to have one more level between &lt;Station&gt; and &lt;Channel&gt;, something like &lt;Instrument&gt;, so that station can have 2 instruments, each having 3 channels. One instrument is very specific BB thing with individual &lt;Response&gt; for each channel, the second instrument is only cheap thing with all properties defined just once for all 3 channels. But this is something for schemaVersion="3.0", I guess ...
