### ISSUE TITLE
tuning up the examples

### ISSUE THREAD

**Issue by PetrColinSky** [FDSN/StationXML#127]
I am referring to the document
https://docs.fdsn.org/projects/stationxml/en/doc_issues/response.html

2.1.1. &lt;Source&gt;
The description reads: Originator of the information contained in the document.”
I would maybe add an example, what it means “originator”. 2.1.3. &lt;Module&gt; below has an example with SeisComp3, but Originator does not, and e.g. here:
https://www.orfeus-eu.org/fdsnws/station/1/query?net=Z3&station=A262A&channel=???&level=response
there is SeisComp3 given in &lt;Source&gt;, and &lt;Module&gt; is missing. Meaning, people maybe interchange Source and Module.

2.3.5 &lt;Latitude&gt; and 2.4.6. &lt;Latitude&gt; and 2.3.6 &lt;Longitude&gt; and 2.4.7. &lt;Longitude&gt;
Examples of &lt;Longitude&gt; and &lt;Latitude&gt; in both Sections are given as plusError=”0.1” and minusError=”0.1”; if we go for „reasonable“ examples, then 0.1 degree looks like really very uncertain station location (+- 10 km), maybe plusError=”0.0001” would look bit more realistic.

2.3.7. &lt;Elevation&gt; and 2.4.8. &lt;Elevation&gt;
Here, on the other hand, error of 10 cm in &lt;Elevation&gt; seems to be bit too optimistic to me.

2.4.15 &lt;SampleRateRatio&gt;
The example is complicated, it is not clear intuitively that the values 2590674 and 3.859999367e-07 are reciprocal. Moreover, they should and are reciprocal just because the &lt;NumberSamples&gt; is =1. It can be any integer. I would simplify the example to something closer to seismological practice, maybe:

&lt;SampleRate&gt;125&lt;/SampleRate&gt;
&lt;SampleRateRatio&gt;
        &lt;NumberSamples&gt;250&lt;/NumberSamples&gt;
        &lt;NumberSeconds&gt;2&lt;/NumberSeconds&gt;
&lt;/SampleRateRatio&gt;

2.4.16 &lt;ClockDrift&gt;
Example again gives 0.1. It should be in seconds per sample, so, I guess, the numbers will be very small. Not sure what are reasonable values, but as the drift can be units of second per day, this number needs to be something in order of 10^-7 for sampling rate of 100 sps and 1 s drift over a day.

There are many other examples, where the value is 0.1, but this I would leave as it is, unless somebody has better numbers.

**Comment by crotwell** [comment]
Source/Sender
-------
I agree, Source and Sender look confusing in their documentation and use. In fact I think Source is probably not really useful at the top level of an stationxml that comes from a datacenter via a query. The originator is likely different for each network. Unfortunately it is required.

Suggest that for stationxml created by a network operator that Source be set and Sender not used. For a data center that is responding to a query, ie just forwarding information, Source be the empty string and Sender be the data center? Idea being that Source being empty string implies that the document is not the original metadata from the network operator?

Or perhaps Source and Sender be the same (current DMC choice).

In version 2.0, could make it so a document can use Source or Sender but not both?

PlusError/MinusError
-----
I agree with your comments on error size. The trouble is that in the schema, plusError is an attribute, via uncertaintyDouble, on FloatType. So the example is on the generic type, instead of being on each
specific element. That is why all the errors are 0.1.

I guess there are 3 choices:
- leave it alone
- remove the example as it doesn't add that much anyway
- try to recode the python conversion to have separate examples for each use of FloatType

I might lean towards option 2, but if there are strong feelings I can look into option 3.

Sample Rate Ratio
----
+1 on a simple example. I think the purpose of this is for really low sample rate channels. So maybe
an example could reflect that, like a 2 samples per day channel. The actual sample rate would be 0.000023148148148148, showing that the accuracy of the ratio is better than the float rate?

```
<SampleRate>0.000023148</SampleRate>
<SampleRateRatio>
<NumberSamples>2</NumberSamples>
<NumberSeconds>86400</NumberSeconds>
</SampleRateRatio>
```

For ver2, should the number of seconds should be a float instead of int? Gives more flexibility in specifying the rate. Or perhaps not as this is nominal sample rate, which should be simple?

Also, there are additional comments about sampleRate that are in the schema on "SampleRateGroup" but they are not being extracted via the converter.

**Comment by PetrColinSky** [comment]
Source / Sender: I like the idea that network operator uses Source and data center uses Sender. The option that Source and Sender are the same is also OK.

PlusError / MinusError: I like to have examples, this is my personal feeling, as a user, I usually get the point from examples, not that much frome a description. So, for me, leaving it as it is is also OK. Anyway, these are more examples on how to use the syntax, not that much about what values should be there.

SampleRateRatio: I like your example, @crotwell. The number 86400 clearly shows it is one day. No strong opinion on if the number of seconds should be float or int. I would keep it simple.

**Comment by crotwell** [comment]
PR #135 does source sender
PR #136 has 2 sample per day example

We are leaving plusminus error as is for now as at least the structure is there.
