### ISSUE TITLE
contents on left in docs show Polynomial as required in Stage

### ISSUE THREAD

**Issue by crotwell** [FDSN/StationXML#52]
On left within [Stage](http://docs.fdsn.org/projects/stationxml/en/draft/reference.html#stage), the docs show:
```
<Polynomial> required
```
but Polynomial is not required in a Stage as it is within an `<xs:choice>`.

**Comment by crotwell** [comment]
fixed in #75

**Comment by PetrColinSky** [comment]
My understanding is, that &lt;Polynomial&gt; is somehow "conditionally" required, when the response is given by a specific way, see 2.5.2 &lt;InstrumentPolynomial&gt;. Usually, an element is required when being inside another element, but here the problem is, that &lt;Polynomial&gt; depends on &lt;InstrumentPolynomial&gt; but is not inside &lt;InstrumentPolynomial&gt;, but it is inside &lt;Stage&gt;, which is at the same level as &lt;InstrumentPolynomial&gt;. Moreover, the description of &lt;Polynomial&gt; uses the term "... a Polynomial Stage is required ... " which may look like there is an element called "Polynomial Stage", which it is not, it is &lt;Polynomial&gt; inside &lt;Stage&gt;. Also, in 2.5.2, the same thing is called "Polynomial stage" with lower-case "s" in "stage".

**Comment by crotwell** [comment]
I updated PR 75 to change "Polynomial Stage" to "Polynomial stage". Hopefully the little s makes it less confusing. 

Yes, the basic idea is if any Stage contains a Polynomial, then InstrumentPolynomial should be used, otherwise InstrumentSensitivity.  I agree the _required_ relationship is complicated. Fixing would require a schema change.
